"""
MD analysis shared infrastructure facade.

Re-exports from shared modules. Does not export GromacsRunner (replaced by
GromacsContext in gromacs_context.py), resolve_protein_posre_paths, or
patch_topology_membrane_restraints.
"""

from .analysis_helpers import (
    mean_std,
    parse_pose_name,
    parse_xvg,
    parse_xvg_columns,
    select_analysis_range,
    ensure_pbc_corrected_trajectory,
    compute_rmsd,
    compute_rmsf,
)
from .constants import (
    GROMACS_FRIENDLY_RANKS,
    ION_RESNAMES,
    LIG_HEAVY_GROUP_NAME,
    LIGAND_RESNAME,
    LIPID_RESNAMES,
    WATER_ION_RESNAMES,
    get_gromacs_friendly_ranks,
)
from .index_ops import (
    detect_ligand_resname_from_gro,
    detect_lipid_resnames_in_gro,
    detect_lipid_resnames_in_top,
    get_ndx_group_index,
    make_membrane_index,
    make_system_index,
    read_gro_atom_count,
    rename_ndx_last_group,
    validate_system_index_groups,
    resolve_ligand_resname_for_pose,
    write_atom_index_group,
    write_bulk_solvent_index,
)
from .gromacs_paths import (
    clean_gro_file,
    get_gromacs_binary,
    get_mdp_dir,
    get_membrane_mdp_dir,
)
from .gromacs_context import GromacsContext
from .gromacs_commands import (
    copy_mdp_files,
    pbc_reimage_trajectory,
    resolve_backbone_group,
    run_md_stage,
    run_mdrun,
    validate_required_file_paths,
)
from .topology_ops import (
    collect_resolved_topology_files,
    collect_posre_includes,
    generate_posre_with_fc,
    generate_staged_restraint_variants,
    patch_topology_staged_restraints,
    posre_variant_path,
    resolve_protein_topology_assets,
    validate_topology_includes,
)
from .grompp_warnings import (
    GromppWarning,
    GromppWarningError,
    GromppWarningPolicy,
    get_approved_grompp_warnings_path,
    load_approved_grompp_warnings,
    parse_grompp_warnings,
    run_grompp,
    save_approved_grompp_warnings,
)
from .ion_solvent import (
    choose_solvent_group_for_genion,
    detect_solvent_group_for_genion,
    get_solvent_box_for_water_model,
    get_solvent_box_path,
    parse_topology_molecule_counts,
    validate_ionic_strength_after_genion,
    validate_system_neutrality_after_genion,
)

__all__ = [
    "GromacsContext",
    "LIGAND_RESNAME",
    "LIG_HEAVY_GROUP_NAME",
    "LIPID_RESNAMES",
    "ION_RESNAMES",
    "WATER_ION_RESNAMES",
    "GROMACS_FRIENDLY_RANKS",
    "clean_gro_file",
    "copy_mdp_files",
    "collect_resolved_topology_files",
    "collect_posre_includes",
    "make_system_index",
    "make_membrane_index",
    "read_gro_atom_count",
    "rename_ndx_last_group",
    "resolve_ligand_resname_for_pose",
    "detect_ligand_resname_from_gro",
    "get_ndx_group_index",
    "validate_system_index_groups",
    "write_atom_index_group",
    "write_bulk_solvent_index",
    "get_gromacs_binary",
    "get_gromacs_friendly_ranks",
    "run_mdrun",
    "run_md_stage",
    "validate_required_file_paths",
    "pbc_reimage_trajectory",
    "resolve_backbone_group",
    "parse_xvg",
    "parse_xvg_columns",
    "select_analysis_range",
    "parse_pose_name",
    "mean_std",
    "ensure_pbc_corrected_trajectory",
    "compute_rmsd",
    "compute_rmsf",
    "get_mdp_dir",
    "get_membrane_mdp_dir",
    "detect_lipid_resnames_in_gro",
    "detect_lipid_resnames_in_top",
    "generate_posre_with_fc",
    "generate_staged_restraint_variants",
    "patch_topology_staged_restraints",
    "posre_variant_path",
    "resolve_protein_topology_assets",
    "validate_topology_includes",
    "GromppWarning",
    "GromppWarningError",
    "GromppWarningPolicy",
    "get_approved_grompp_warnings_path",
    "load_approved_grompp_warnings",
    "save_approved_grompp_warnings",
    "parse_grompp_warnings",
    "run_grompp",
    "get_solvent_box_for_water_model",
    "get_solvent_box_path",
    "parse_topology_molecule_counts",
    "detect_solvent_group_for_genion",
    "choose_solvent_group_for_genion",
    "validate_ionic_strength_after_genion",
    "validate_system_neutrality_after_genion",
]
