"""
Agent utility functions for MD analysis pipeline.

Functions exposed to the agent for building file paths and discovering tool paths.
Includes both the soluble-protein pipeline and the transmembrane-protein pipeline.
"""

import glob
import os
from typing import Any, Optional

from agents import function_tool

from ...logger_utils import get_logger


def build_file_paths_impl(
    md_workdir: str = None,
    existing_md_root: str = None,
    protein_gro: str = None,
    protein_top: str = None,
    posre_itp: str = None,
    docking_csv: str = None,
    ligand_input: str = None,
    poses_dir: str = None,
    protein_file: str = None,
    membrane_system_gro: str = None,
    membrane_system_top: str = None,
    existing_membrane_dir: str = None,
    membrane: bool = False,
) -> Any:
    """
    Build file_paths dictionary from explicit paths, filtering out None/empty values.

    This dictionary is the single source of truth for ALL paths (directories and files).
    It consolidates what was previously split between dir_structure and file_paths.

    Use this function to initialize the file_paths dictionary before calling any MD module.
    The returned dictionary should be passed to each module tool function.

    Supports both the **soluble protein + ligand** pipeline and the
    **transmembrane protein** pipeline.  Provide the appropriate subset of
    arguments for the workflow you intend to run.

    Args:
        md_workdir: MD working directory root (used to derive other dirs if not provided).
                   Creates a new md_analysis/ subdirectory structure.
                   For membrane runs, also creates a membrane/ subdirectory.
        existing_md_root: Path to an existing md_analysis directory to discover files from.
                         Use this to continue/resume from a previous run.
                         If provided, will scan for existing files and populate paths.
        protein_file: Path to input protein PDB file (must be protonated).
        protein_gro: Path to protein GRO file (output from ProteinTopology)
        protein_top: Path to protein topology file (output from ProteinTopology)
        posre_itp: Path to position restraints file (output from ProteinTopology via pdb2gmx)
        docking_csv: Path to docking results CSV (input for LigPrepare)
        ligand_input: Ligand structure input - can be:
            - SMILES string: "CC(=O)O" (for single ligand only)
            - CSV file: Path to CSV with SMILES column (flexible column names)
            - SDF/MOL2 file: Path to structure file
            - Directory: Path containing structure files
        poses_dir: Directory containing pose subdirectories (used by Gro and StabilityAnalysis)
        membrane_system_gro: Path to pre-built membrane system GRO (from CHARMM-GUI).
            When provided together with membrane_system_top, the membrane pipeline
            uses the pre-built import pathway.
        membrane_system_top: Path to pre-built membrane system topology.
        existing_membrane_dir: Path to an existing membrane working directory to
            discover/resume from.
        membrane: If True, create a membrane/ subdirectory. Membrane runs still
            require membrane_system_gro + membrane_system_top at preparation time.
            Automatically set when membrane_system_gro or membrane_system_top are provided.

    Returns:
        dict: File paths dictionary with only non-empty values

    Directory keys (auto-created from md_workdir if provided):
        - md_root: Root MD analysis directory
        - protein_dir: Directory for protein topology files
        - poses_dir: Directory containing pose subdirectories
        - reports_dir: Directory for analysis reports
        - membrane_dir: Directory for membrane preparation (when membrane args given)
        - membrane_reports_dir: Analysis reports for membrane pipeline

    File keys (explicitly provided or generated by pipeline steps):
        - protein_file: Input protein PDB file
        - protein_gro: Protein structure in GRO format
        - protein_top: Protein topology file
        - posre_itp: Position restraints ITP file (created alongside protein_top)
        - docking_csv: Docking results CSV
        - ligand_input: Ligand structure input (SMILES string, CSV, SDF, MOL2, or directory)
        - membrane_system_gro: Pre-built membrane system GRO
        - membrane_system_top: Pre-built membrane system topology

    Example:
        >>> # Soluble pipeline - start fresh
        >>> file_paths = build_file_paths(
        ...     md_workdir="/path/to/output",
        ...     protein_file="/path/to/protein.pdb",
        ...     ligand_input="/path/to/ligands.csv"
        ... )

        >>> # Membrane pipeline - pre-built system
        >>> file_paths = build_file_paths(
        ...     md_workdir="/path/to/output",
        ...     protein_file="/path/to/protein.pdb",
        ...     membrane_system_gro="/path/to/step5_input.gro",
        ...     membrane_system_top="/path/to/topol.top",
        ... )

        >>> # Resume from existing membrane run
        >>> file_paths = build_file_paths(
        ...     existing_membrane_dir="/path/to/output/membrane",
        ... )
    """
    paths = {}

    # --- Discovery from existing directories ---
    if existing_membrane_dir and os.path.isdir(existing_membrane_dir):
        paths.update(_discover_membrane_file_paths(existing_membrane_dir))

    if existing_md_root and os.path.isdir(existing_md_root):
        paths.update(discover_file_paths(existing_md_root))
        if "md_root" in paths and "reports_dir" not in paths:
            paths["reports_dir"] = os.path.join(paths["md_root"], "reports")

    # --- Create directory structure from md_workdir ---
    if md_workdir and "md_root" not in paths:
        md_root = os.path.join(md_workdir, "md_analysis")
        paths["md_root"] = md_root
        paths["protein_dir"] = os.path.join(md_root, "protein")
        paths["poses_dir"] = os.path.join(md_root, "poses")
        paths["reports_dir"] = os.path.join(md_root, "reports")

    # Create membrane directory when membrane inputs are given or flag is set
    is_membrane_run = membrane or membrane_system_gro or membrane_system_top or existing_membrane_dir
    if is_membrane_run and md_workdir and "membrane_dir" not in paths:
        membrane_dir = os.path.join(md_workdir, "membrane")
        paths["membrane_dir"] = membrane_dir
        paths["membrane_reports_dir"] = os.path.join(membrane_dir, "reports")

    # --- Explicit file paths ---
    if protein_file:
        paths["protein_file"] = protein_file
    if protein_gro:
        paths["protein_gro"] = protein_gro
    if protein_top:
        paths["protein_top"] = protein_top
    if posre_itp:
        paths["posre_itp"] = posre_itp
    if docking_csv:
        paths["docking_csv"] = docking_csv
    if ligand_input:
        paths["ligand_input"] = ligand_input
    if poses_dir:
        paths["poses_dir"] = poses_dir
    if membrane_system_gro:
        paths["membrane_system_gro"] = membrane_system_gro
    if membrane_system_top:
        paths["membrane_system_top"] = membrane_system_top

    return paths


@function_tool
def build_file_paths(
    md_workdir: str = None, existing_md_root: str = None,
    protein_gro: str = None, protein_top: str = None,
    posre_itp: str = None, docking_csv: str = None,
    ligand_input: str = None, poses_dir: str = None,
    protein_file: str = None, membrane_system_gro: str = None,
    membrane_system_top: str = None, existing_membrane_dir: str = None,
    membrane: bool = False,
) -> Any:
    """Build file_paths dictionary from explicit paths (agent-facing wrapper)."""
    return build_file_paths_impl(**{k: v for k, v in locals().items()})


def discover_file_paths(md_root: str) -> Any:
    """
    Discover existing files and directories from an MD analysis directory structure.

    Use this to resume or continue from an existing run by scanning the directory
    and populating file_paths with discovered files.

    Args:
        md_root: Path to the MD analysis root directory (e.g., .../md_analysis/)
                 This should be the directory containing protein/, poses/, reports/

    Returns:
        dict: file_paths dictionary populated with discovered paths

    Directory structure expected:
        md_root/
        ├── protein/           # protein_dir
        │   ├── protein.gro    # protein_gro
        │   ├── topol.top      # protein_top
        │   └── posre.itp      # posre_itp
        ├── poses/             # poses_dir
        │   └── {ligand}_pocket_{grid}_top{rank}/
        └── reports/           # reports_dir
    """
    logger = get_logger()

    if not os.path.isdir(md_root):
        raise FileNotFoundError(f"MD root directory not found: {md_root}")

    paths = {"md_root": md_root}

    protein_dir = os.path.join(md_root, "protein")
    if os.path.isdir(protein_dir):
        paths["protein_dir"] = protein_dir

        protein_gro = os.path.join(protein_dir, "protein.gro")
        if os.path.exists(protein_gro):
            paths["protein_gro"] = protein_gro

        protein_top = os.path.join(protein_dir, "topol.top")
        if os.path.exists(protein_top):
            paths["protein_top"] = protein_top

        posre_itp = os.path.join(protein_dir, "posre.itp")
        if os.path.exists(posre_itp):
            paths["posre_itp"] = posre_itp

    poses_dir = os.path.join(md_root, "poses")
    if os.path.isdir(poses_dir):
        paths["poses_dir"] = poses_dir

    reports_dir = os.path.join(md_root, "reports")
    if os.path.isdir(reports_dir):
        paths["reports_dir"] = reports_dir

        for report_type, pattern in [
            ("summary_report", "md_analysis_summary_*.csv"),
            ("brief_report", "brief_report_*.csv"),
        ]:
            matches = glob.glob(os.path.join(reports_dir, pattern))
            if matches:
                paths[report_type] = max(matches, key=os.path.getmtime)

    logger.info(f"Discovered file_paths from {md_root}:")
    for key, value in paths.items():
        logger.info(f"  {key}: {value}")

    return paths



def _discover_membrane_file_paths(membrane_dir: str) -> dict:
    """
    Discover existing files from a membrane working directory.

    Args:
        membrane_dir: Path to the membrane working directory.

    Returns:
        dict: file_paths populated with discovered paths.
    """
    logger = get_logger()

    if not os.path.isdir(membrane_dir):
        raise FileNotFoundError(f"Membrane directory not found: {membrane_dir}")

    paths: dict[str, str] = {"membrane_dir": membrane_dir}

    # Look for key files
    candidates = {
        "membrane_min_gro": "min.gro",
        "membrane_ndx": "index.ndx",
        "membrane_posre": "posre.itp",
        "membrane_md_tpr": "md.tpr",
        "membrane_md_xtc": "md.xtc",
        "membrane_md_gro": "md.gro",
    }

    for key, filename in candidates.items():
        fpath = os.path.join(membrane_dir, filename)
        if os.path.exists(fpath):
            paths[key] = fpath

    # Recover topology path robustly across common naming/layouts.
    top_candidates = [
        os.path.join(membrane_dir, "system.top"),
        os.path.join(membrane_dir, "topol.top"),
    ]
    for top_path in top_candidates:
        if os.path.exists(top_path):
            paths["membrane_top"] = top_path
            break
    if "membrane_top" not in paths:
        recursive_top = glob.glob(os.path.join(membrane_dir, "**", "*.top"), recursive=True)
        if recursive_top:
            # Prefer shortest relative path (top-level topology root when present).
            best_top = min(
                recursive_top,
                key=lambda p: (os.path.relpath(p, membrane_dir).count(os.sep), len(p)),
            )
            paths["membrane_top"] = best_top

    reports_dir = os.path.join(membrane_dir, "reports")
    if os.path.isdir(reports_dir):
        paths["membrane_reports_dir"] = reports_dir
        report_files = glob.glob(
            os.path.join(reports_dir, "membrane_analysis_*.csv")
        )
        if report_files:
            paths["membrane_analysis_report"] = max(
                report_files, key=os.path.getmtime
            )

    logger.info(f"Discovered membrane file_paths from {membrane_dir}:")
    for key, value in paths.items():
        logger.info(f"  {key}: {value}")

    return paths


@function_tool
def discover_paths(
    gromacs_path: Optional[str] = None,
    ambertools_path: Optional[str] = None,
) -> Any:
    """
    Discover GROMACS and AmberTools installation paths from conda environment.

    Call before running any MD modules; merge the returned dict into file_paths.
    Matches scripts/install.sh layout (same logic on Linux and macOS):
    - Linux + GPU: only gromacs-2024.4/cuda/bin
    - Linux no-GPU: only conda bin ($CONDA_PREFIX/bin/gmx)
    - macOS: only conda bin, or gromacs-2024.4/bin if conda failed and source build was used
    One deterministic order: cuda/bin → conda bin → gromacs-2024.4/bin (first that exists).

    Args:
        gromacs_path: Optional explicit path to GROMACS bin directory. If provided and valid,
                     returns immediately with inferred binary type.
        ambertools_path: Optional explicit path to AmberTools home. If omitted, uses CONDA_PREFIX.

    Returns:
        dict with gromacs_path, ambertools_path, gromacs_binary_type ("cuda" or "standard").

    Raises:
        EnvironmentError: If paths cannot be discovered (run scripts/install.sh or set gromacs_path).
    """
    logger = get_logger()

    # User provided gromacs_path: infer binary type, then one lightweight check.
    if gromacs_path:
        path_norm = gromacs_path.replace(os.sep, "/").rstrip("/")
        if path_norm.endswith("gromacs-2024.4/cuda/bin"):
            binary_type = "cuda"
        elif "gromacs-2024.4" in path_norm:
            binary_type = "standard"
        else:
            binary_type = "standard"
        ambertools_path = ambertools_path or os.environ.get("CONDA_PREFIX")
        if not ambertools_path:
            raise EnvironmentError("CONDA_PREFIX not set. Activate the ADAMS conda environment (scripts/install.sh).")
        if not os.path.isdir(gromacs_path):
            raise EnvironmentError(f"GROMACS bin directory not found: {gromacs_path}")
        if ambertools_path != os.environ.get("CONDA_PREFIX") and not os.path.isdir(ambertools_path):
            raise EnvironmentError(f"AmberTools home not found: {ambertools_path}")
        logger.info(
            f"Using provided paths: GROMACS={gromacs_path}, binary_type={binary_type}"
        )
        return {
            "gromacs_path": gromacs_path,
            "ambertools_path": ambertools_path,
            "gromacs_binary_type": binary_type,
        }

    conda_prefix = os.environ.get("CONDA_PREFIX")
    if not conda_prefix:
        raise EnvironmentError(
            "CONDA_PREFIX not set. Set gromacs_path and ambertools_path explicitly or activate the conda environment."
        )

    # Deterministic order matching install.sh (Linux + macOS). Linux GPU → cuda/bin only;
    # Linux no-GPU / macOS → conda bin; macOS source fallback → gromacs-2024.4/bin.
    cuda_bin_dir = os.path.join(conda_prefix, "gromacs-2024.4", "cuda", "bin")
    conda_bin_dir = os.path.join(conda_prefix, "bin")
    source_bin_dir = os.path.join(conda_prefix, "gromacs-2024.4", "bin")

    if os.path.isdir(cuda_bin_dir):
        gromacs_path = cuda_bin_dir
        binary_type = "cuda"
    elif os.path.isfile(os.path.join(conda_bin_dir, "gmx")):
        gromacs_path = conda_bin_dir
        binary_type = "standard"
    elif os.path.isdir(source_bin_dir):
        gromacs_path = source_bin_dir
        binary_type = "standard"
    else:
        raise EnvironmentError(
            "GROMACS not found. Run the ADAMS install (scripts/install.sh) or set gromacs_path explicitly."
        )

    ambertools_path = ambertools_path or conda_prefix
    if ambertools_path != conda_prefix and not os.path.isdir(ambertools_path):
        raise EnvironmentError(f"AmberTools home not found: {ambertools_path}")

    logger.info(
        f"Discovered paths: GROMACS={gromacs_path}, AMBERHOME={ambertools_path}, "
        f"binary_type={binary_type}"
    )

    return {
        "gromacs_path": gromacs_path,
        "ambertools_path": ambertools_path,
        "gromacs_binary_type": binary_type,
    }
